export default {
  AIR_QUALITY: 'Air Quality',
  CELSIUS: 'C',
  DEGREE: '°',
  ENTER_CITY: 'Enter city ...',
  ERROR: 'Something went wrong. Please contact your administrator.',
  ERROR_ACCESS_DENIED: 'You do not have access to get weather information.',
  ERROR_WRONG_CITY_NAME: 'We could not find weather information for the location above.',
  FAHRENHEIT: 'F',
  HUMIDITY: 'Humidity',
  KPH: 'KPH',
  LOADING: 'Loading...',
  MODERATE: 'Moderate',
  MPH: 'MPH',
  CENTER_POINT: '•',
  WELCOME_TEXT: 'Which location weather would you like to know ?',
  WIND: 'Wind',
};
